### ISSUE TITLE
Tag fetching

### ISSUE THREAD

**Issue by Alystrasz** [R2Northstar/VerifiedMods#17]
When the `verify_versions.py` script fetches tags of a mod repository, it only accesses the first tag page (*e.g.* https://api.github.com/repos/{}/{}/tags), while tags resource is paginated (*i.e.* searched tag might not be on the first results page).

See https://github.com/R2Northstar/VerifiedMods/pull/16#issuecomment-1884912482 for pages example.

**Comment by Dinorush** [comment]
From what I can gather, there is indeed no way to reorder or increase the number of tags fetched. One possible alternative is to instead pull the tag from the latest release instead, e.g. `https://api.github.com/repos/{}/{}/releases/latest`.
