### ISSUE TITLE
Add JSON schema to validate structure of `mods.json`

### ISSUE THREAD

**Issue by GeckoEidechse** [R2Northstar/VerifiedMods#7]
A JSON schema is a JSON file that describes the structure of a JSON file.

Defining a JSON schema would allow us to automatically verify the structure of the `mod.json` and automatically throw an error in CI if someone PRs an incorrect JSON file ^^

See also https://json-schema.org/overview/what-is-jsonschema

**Comment by Alystrasz** [comment]
On it

**Comment by GeckoEidechse** [comment]
Closed by #11
